version: '3.3'
services:
    mysql:
     image: "mariadb:10.7"
     container_name: zoneminder_db
     restart: always
     volumes:
     - "mysql:/var/lib/mysql"
     ports:
     - "3306:3306"
     env_file:
      - ./config
    zoneminder: 
     container_name: zoneminder
     restart: always
     env_file:
      - ./config
     image: rpi-zoneminder:latest
     build:
      context: ./
      args:
       ZM_DB_HOST: ${ZM_DB_HOST}
       ZM_DB_NAME: ${ZM_DB_NAME}
       ZM_DB_USER: ${ZM_DB_USER}
       ZM_DB_PASS: ${ZM_DB_PASS}
     ports: 
     - "8080:80"
     - "9000:9000"
     - "6802:6802"
     volumes:
     - "zoneminder:/mnt/zoneminder/data:rw"
     environment:
     - TZ=Europe/Berlin
     - ZM_DB_HOST=mysql
     shm_size: "7gb"
volumes:
      mysql:
      zoneminder:
